Feature/task7 homework
tekerrr/skillbox_laravel pull request #2
Opened 2019-12-05 09:10 UTC by tekerrr

2019-12-06 12:44 UTC, mvsvolkov requested changes

2019-12-06 12:44 UTC, mvsvolkov commented on app/Http/Controllers/Admin/NewsController.php
> +        ]);
Правила валидация очень похожи для методов добавления и обновление, возможно, будет лучше вынести их в отдельные FormRequest объекты и наследовать один от другого, чтобы скорректировать разные правила валидации.

Это поможет избавиться от дублирования

2019-12-06 12:44 UTC, mvsvolkov commented on app/Http/Controllers/CommentController.php
> +        ;
Получать commentable_id из формы - это не очень хорошее решение. Используйте разные маршруты для добавления комментариев к разным объектам. И тогда эта проблема решиться структурой url)

2019-12-06 12:44 UTC, mvsvolkov commented on app/Statistics.php
> +        ;
Некорректно учтено задание: "Средние количество статей у “активных” пользователей, при этом активным пользователь считается, если у него есть более 1-й статьи" - т.е. у автора строго > 1 статьи, Ваш запрос этого не учитывает.

2019-12-06 12:44 UTC, mvsvolkov commented on database/migrations/2019_11_06_104919_create_taggables_table.php
> +        Schema::create('taggables', function (Blueprint $table) {
В данной задаче это не ошибка, но просто дополнительная информация. Для боевого проекта - так сделать нельзя. Вы же не сможете перемигрировать всю БД, в которой есть полезные данные. Поэтому для уже боевого проекта - нужно было бы создать новую миграцию, создающую новую таблицу - перекидывающую в нее данные из старой и удаляющую старую таблицу

2019-12-09 07:51 UTC, tekerrr commented on database/migrations/2019_11_06_104919_create_taggables_table.php
> +        Schema::create('taggables', function (Blueprint $table) {
Вариант решения в ветке https://github.com/tekerrr/skillbox_laravel/tree/test/task7_migration

2019-12-10 08:29 UTC, mvsvolkov commented on tests/Feature/Common/CommentsTest.php
> +            'commentable_id' => $post->id,
Это уже лишнее для тестов по созданию комментариев

2019-12-11 08:12 UTC, merged